### ISSUE TITLE
Redirect loop when trying to access a private Node-RED editor

### ISSUE THREAD

**Issue by ZJvandeWeg** [FlowFuse/flowforge#1184]
### Current Behavior

When someone shares a link to a NR instance a signed in (on FlowForge ) user doesn't have access too, that user is stuck in a redirect loop. This loop does expose the project exists because of the editor theming.

### Expected Behavior

A 403 is presented to the user, which might leak the existance of a project. Otherwise we should render a 404?

### Environment

- FlowForge version: v1.0
- Node.js version:
- npm version:
- Platform/OS: MacOSX
- Browser: Chrome

**Comment by knolleary** [comment]
We added the 'auto login' flag to Node-RED in 3.x which removes the need for the user to click a button to trigger the login flow.

There is logic there to avoid this type of loop in case of an error - but not all oauth errors surface in the same way and it looks like this scenario doesn't trigger the right logic.

The fix could be in one of three places:

 - Node-RED's own error handling
 - Our login plugin's error handler (`nr-auth`)
 - FlowForge's handling of errors and how it is returning them

**Comment by ZJvandeWeg** [comment]
As the majority of all new instances on FlowForge is 3.x, I vote this is a "wont-fix" issue and we close it. cc @MarianRaphael

**Comment by lgrkvst** [comment]
Possible related to https://github.com/flowforge/flowforge/issues/2841, and maaaaybe https://github.com/flowforge/flowforge/issues/2582. Very much an issue despite on 3.x.
